version: "3.8"

include:
  - ./proxy.yaml

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    restart: always
    depends_on:
      - db
    networks:
      backend:
        ipv4_address: 172.20.0.5
    
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    # restart: on-failure
    networks:
      backend:
        ipv4_address: 172.20.0.10
  
       
