version: "3.8"

include:
  - ./proxy.yaml

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    env_file:
      - .env.app
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.0.5
    
  db:
    image: mysql:8
    env_file:
     - .env.db
#    restart: on-failure
    networks:
      backend:
        ipv4_address: 172.20.0.10
  
       
