version: "3.8"

include:
  - ./proxy.yaml

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    environment:
      - DB_HOST=db
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    restart: always
    depends_on:
      - db
    networks:
      backend:
        ipv4_address: 172.20.0.5
    
  db:
    image: mysql:8
    env_file:
      - .env
    # restart: on-failure
    networks:
      backend:
        ipv4_address: 172.20.0.10
  
       
